version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: eslint
    versions:
    - 4.19.1
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
